services:
  leafy-bank-backend-transactions:
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile.backend
    image: leafy-bank-backend-transactions-image:latest
    ports:
      - "8001:8001"
    restart: always
    container_name: leafy-bank-backend-transactions-container