env:
  NODE_ENV: prod
  
# Secret environment variables (references to K8s secrets)
envSecrets:
  # Server-side (for API routes)
  MONGODB_URI: leafy-bank-backend-transactions
  ORIGINS: leafy-bank-backend-transactions

serviceAccount:
  enabled: true
  create: false  # Don't create a new service account
  name: irsa  # Use the existing one