env:
  NODE_ENV: staging
  
envSecrets:
  MONGODB_URI: leafy-bank-backend-transactions
  ORIGINS: leafy-bank-backend-transactions

serviceAccount:
  enabled: true
  create: false  # Don't create a new service account
  name: irsa  # Use the existing one